version: "3.7"

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    environment:
      - DATABASE_URL=postgresql://postgres:my-secure-password@postgres:5432/pid

    command:
      ["sh", "-c", "flask --app core.app.server db upgrade && python app.py"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.5-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-secure-password
      - POSTGRES_DB=pid
      - TZ=America/Sao_Paulo

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
